# Generated by Django 5.2.5 on 2025-08-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0002_galeria_delete_receita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeria',
            old_name='title',
            new_name='car1',
        ),
        migrations.RenameField(
            model_name='galeria',
            old_name='description',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='galeria',
            old_name='image',
            new_name='image1',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='galeria',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='galerias/images/'),
        ),
        migrations.AddField(
            model_name='galeria',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='galerias/images/'),
        ),
    ]
