# Generated by Django 5.2.5 on 2025-08-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0003_rename_title_galeria_car1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeria',
            old_name='car1',
            new_name='car',
        ),
    ]
